### ISSUE TITLE
There aren't enough caps in the name

### ISSUE THREAD

**Issue by cujomalainey** [DavidSkrundz/CMPUT291MINIPROJECTONE#1]
nuff said

**Comment by DavidSkrundz** [comment]
can we have your sample data?

**Comment by cujomalainey** [comment]
Yea, but for your demo you have to generate your own cause I'm pretty sure they count it for marks.

**Comment by DavidSkrundz** [comment]
they supply the rows for the demo

**Comment by DavidSkrundz** [comment]
thats not data...

**Comment by cujomalainey** [comment]
check pull requests, the stupid thing uploaded the icon not the file
